### ISSUE TITLE
Getting a cover image

### ISSUE THREAD

**Issue by shiva-p17** [RunasSudo/reader.js#1]
Hi 

Is there a possible to get book cover image?

**Comment by RunasSudo** [comment]
Is there any particular purpose you'd like to use the cover image for?

In general, you should be able to get the cover image in the same way as any other epub resource:

    var id = epubContent.find("meta[name='cover']").attr('content');
    var path = resolveID(id);
    $.get(book + path, ...); // Access the cover

**Comment by shiva-p17** [comment]
@RunasSudo 
Thank you so much  for your time :)

I did as follows, please correct it if I'm wrong 
```
$.get(book + "META-INF/container.xml", function(container) {
	
	
	opfPath = $(container).find("rootfile").attr("full-path");
	console.log("Loading " + book + opfPath);
	$.get(book + opfPath, function(content) {	
		epubContent = $(content);
			var children= epubContent.find("manifest").children();
			for(var i = 0; i< children.length;i++)
			{
				if (children[i].getAttribute('id') == 'cover-image') // any attribute could be used here
				{
		
					cover_image=children[i].getAttribute('href');
					
				break;    }  }}, "xml");}, "xml");
```

**Comment by shiva-p17** [comment]
Hi 
Can you please check my solution.

Thanks.

**Comment by RunasSudo** [comment]
Depending on your use case, you may not want to hard-code the ID of the cover image. The ID is stored in the `<meta name="cover" ...>` tag, so you can do:

    var epubContent = $(content);
    var id = epubContent.find("meta[name='cover']").attr("content");

Instead of manually walking through all the children in the `for` loop, you can also simply then do:

    var cover_image = epubContent.find("item#" + id).attr("href");

**Comment by shiva-p17** [comment]
Hi RunasSudo,

 Yes you are right. Thanks :)
